#!/bin/bash

clear
echo "========================================="
echo "          WINGS3 INSTALLER"
echo "========================================="
echo ""

read -p "Type YES to start installation: " START
if [[ "$START" != "YES" ]]; then
    echo "Installation cancelled."
    exit 0
fi

echo ""
echo "[1/7] Installing Docker Compose..."
apt update
apt install docker-compose -y

echo ""
echo "[2/7] Creating Pterodactyl Wings directory..."
mkdir -p pterodactyl/wings
cd pterodactyl/wings || exit 1

echo ""
echo "[3/7] Creating docker-compose.yml..."

cat > docker-compose.yml <<'EOF'
version: '3.8'

services:
  wings:
    image: ghcr.io/pterodactyl/wings:v1.6.1
    restart: always
    networks:
      - wings0
    ports:
      - "8080:8080"
      - "2022:2022"
      - "443:443"
    tty: true
    environment:
      TZ: "UTC"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/
      - /etc/pterodactyl/:/etc/pterodactyl/
      - /var/lib/pterodactyl/:/var/lib/pterodactyl/
      - /var/log/pterodactyl/:/var/log/pterodactyl/
      - /tmp/pterodactyl/:/tmp/pterodactyl/
      - /etc/ssl/certs:/etc/ssl/certs:ro
      # Optional: If upgrading from older daemon versions
      # - /srv/daemon-data/:/srv/daemon-data/
      # Optional: Required for SSL if using Let's Encrypt
      # - /etc/letsencrypt/:/etc/letsencrypt/

networks:
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
    driver_opts:
      com.docker.network.bridge.name: wings0
EOF

echo "docker-compose.yml created."

echo ""
echo "[4/7] Starting Wings..."
docker compose up -d

echo ""
echo "[5/7] Starting Serveo tunnel..."
echo "Run this command in another terminal if required:"
echo "ssh -R 80:localhost:443 serveo.net"

echo ""
echo "[6/7] Moving to Pterodactyl directory..."
cd ../.. || exit 1

echo ""
echo "========================================="
echo " CONFIGURATION REQUIRED"
echo "========================================="
echo ""
echo "Open:"
echo "nano /etc/pterodactyl/config.yml"
echo ""
echo "Paste the Wings configuration generated by your Pterodactyl Panel."
echo ""

read -p "Type YES after saving config.yml to continue: " CONFIG

if [[ "$CONFIG" != "YES" ]]; then
    echo "Setup paused."
    exit 0
fi

echo ""
echo "[7/7] Recreating Wings container..."
cd wings || exit 1
docker compose up -d --force-recreate

echo ""
echo "========================================="
echo "       WINGS3 INSTALLER COMPLETE"
echo "========================================="
echo ""
echo "Wings container status:"
docker compose ps
